spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yanger?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 1234
    # Redis数据库索引（默认为0）
    database: 0
    timeout: 0
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 30
      # 连接池中的最大空闲连接
      max-idle: 5
      # 连接池中的最小空闲连接
      min-idle: 0
  cache:
    type: redis     
  session:
    store-type: redis